import React from 'react'
import { ArrowLeft, AlertTriangle } from 'lucide-react'

function Disclaimer({ onBack }) {
  return (
    <div className="max-w-3xl mx-auto">
      <button
        onClick={onBack}
        className="flex items-center gap-2 text-blue-600 dark:text-blue-400 hover:underline mb-6"
      >
        <ArrowLeft className="w-4 h-4" aria-hidden="true" />
        Back to Will Generator
      </button>

      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 p-6 md:p-8">
        <div className="flex items-center gap-3 mb-6">
          <AlertTriangle className="w-8 h-8 text-amber-500" aria-hidden="true" />
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Legal Disclaimer</h2>
        </div>

        <div className="prose dark:prose-invert max-w-none space-y-6 text-gray-700 dark:text-gray-300">
          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Not Legal Advice
            </h3>
            <p>
              Willful Estate provides a template for informational and educational purposes only.
              This tool does not constitute legal advice, and using it does not create an
              attorney-client relationship.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              No Guarantee of Validity
            </h3>
            <p>
              While this tool aims to help you create a basic will document, we cannot guarantee
              that the resulting document will be legally valid in your jurisdiction. Laws regarding
              wills vary by state and are subject to change.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              When to Consult an Attorney
            </h3>
            <p>We strongly recommend consulting a licensed estate planning attorney if you have:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>A complex estate or significant assets</li>
              <li>Business ownership interests</li>
              <li>A blended family or complicated family dynamics</li>
              <li>Concerns about potential will contests</li>
              <li>Special needs beneficiaries</li>
              <li>Real estate in multiple states</li>
              <li>Tax planning concerns</li>
            </ul>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Execution Requirements
            </h3>
            <p>
              For a will to be legally valid, it must be properly executed according to your state's
              laws. Generally, this requires:
            </p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>Being of legal age (18 in most states) and sound mind</li>
              <li>Signing the will in the presence of witnesses</li>
              <li>Having witnesses sign the will (number varies by state)</li>
              <li>Optionally, having the will notarized for a self-proving affidavit</li>
            </ul>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Limitation of Liability
            </h3>
            <p>
              The creators of Willful Estate shall not be held liable for any damages, losses, or
              legal issues arising from the use of this tool or any documents generated by it. Use
              this tool at your own risk and discretion.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Keep Your Will Updated
            </h3>
            <p>
              Life circumstances change. Review and update your will after major life events such as
              marriage, divorce, births, deaths, significant changes in assets, or moving to a new
              state.
            </p>
          </section>

          <p className="text-sm text-gray-600 dark:text-gray-300 pt-4 border-t border-gray-200 dark:border-gray-700">
            Last updated: February 2026
          </p>
        </div>
      </div>
    </div>
  )
}

export default Disclaimer
